apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:dind
    readinessProbe:
      exec:
        command: [sh, -c, "ls -S /var/run/docker.sock"]
    command:
    - sleep
    args:
    - 99d
