podTemplate (yaml: '''
              apiVersion: v1
              kind: Pod
              spec:
                volumes:
                - name: docker-socket
                  emptyDir: {}
                containers:
                - name: docker
                  image: docker:19.03.1
                  volumeMounts:
                  - name: docker-socket
                    mountPath: /var/run
                - name: docker-daemon
                  image: docker:19.03.1-dind
                  securityContext:
                    privileged: true
                  volumeMounts:
                  - name: docker-socket
                    mountPath: /var/run
''') {
    node(POD_LABEL) {
        def app

        stage('Clone repository') {
            checkout scm
        }

        stage('Build image') {
            app = docker.build("gbt55/discord-bot-music", "./app")
        }

        // stage('Test image') {
    

        //     app.inside {
        //         sh 'echo "Tests passed"'
        //     }
        // }

        stage('Push image') {
            
            docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                app.push("v1.0.${env.BUILD_NUMBER}")
            }
        }
        
        stage('Trigger ManifestUpdate') {
                    echo "triggering updatemanifestjob"
                    build job: 'pipeline-updatemanifest-discord-bot-music', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
            }
    }
}