podTemplate (yaml: '''
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: dind
                  image: docker:dind
                  readinessProbe:
                    exec:
                      command: [sh, -c, "docker ps"]
                  securityContext:
                    privileged: true
''') {
    node(POD_LABEL) {
        def app

        stage('Clone repository') {
            container('dind')
            {
                checkout scm
            }
            
        }

        stage('Build image') {
            container('dind'){
                app = docker.build("gbt55/discord-bot-music", "./app")
            }
            
        }

        // stage('Test image') {
    

        //     app.inside {
        //         sh 'echo "Tests passed"'
        //     }
        // }

        stage('Push image') {
            container('dind'){
                docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                app.push("v1.0.${env.BUILD_NUMBER}")
                }
            }
            
        }
        
        stage('Trigger ManifestUpdate') {
                    echo "triggering updatemanifestjob"
                    build job: 'UM-musicbot', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
            }
    }
}